language: objective-c

osx_image: xcode7.1

before_install:
 - xcodebuild -showsdks
 - gem install cocoapods -v '0.39.0'
script:
 # Objectve-C tests
 - xctool test -workspace ably.xcworkspace -scheme ably -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 # Swift tests
 - xctool test -workspace ably.xcworkspace -scheme ablySpec -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
