language: objective-c

osx_image: xcode7.1

before_install:
  - gem install cocoapods -v '0.39.0'
script: 
 - xcodebuild test -workspace ably.xcworkspace -scheme ablySpec -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
