language: objective-c

osx_image: xcode6.4

before_install:
  - gem install cocoapods -v '0.38.2'
script: 
 - xcodebuild test -workspace ably-ios.xcworkspace -scheme ablySpec -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 

