language: objective-c
osx_image: xcode7.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  # Show available SDKs
  - xcodebuild -showsdks
  # Show available simulators
  - xcrun simctl list devices
install:
  # Xcode Build formatter
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  # Custom formatter for xcpretty with some syntactic sugar for presentation on TravisCI
  # https://github.com/kattrali/xcpretty-travis-formatter
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  # Install CocoaPods
  - gem install cocoapods -v '0.39.0' --no-rdoc --no-ri --no-document --quiet
  - pod install
script:
  # Run tests
  - BUILDTOOL=xctool ./Scripts/run-tests.sh