language: objective-c
script: xcodebuild -workspace ably-ios.xcworkspace -scheme ably -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO
xctool test -workspace ably-ios.xcworkspace -scheme ably -sdk iphonesimulator8.1 ONLY_ACTIVE_ARCH=NO 

