language: objective-c
script:
  -xctool -workspace ably-ios.xcworkspace -scheme ably -sdk iphonesumulator7.0 ONLY_ACTIVE_ARCH=NO
  -xctool test -workspace ably-ios.xcworkspace -scheme ably -sdk iphonesumulator7.0 ONLY_ACTIVE_ARCH=NO
